import type { CategoryDefinition, SituationCategory } from "../types";

export const CATEGORIES: Record<
  Exclude<SituationCategory, "None">,
  CategoryDefinition
> = {
  Company: {
    id: "Company",
    label: "회사",
    keywords: [
      "출근", "퇴근", "회사", "부장", "팀장", "상사", "과장", "회의",
      "야근", "결재", "보고서", "월요일", "메신저", "슬랙", "카톡방",
      "업무", "실적", "보고", "발표자료",
    ],
    characterStyleTags: ["office", "necktie"],
    backgroundIds: ["bg_company_hall", "bg_subway", "bg_office_floor"],
    obstacleIds: ["obs_document", "obs_boss", "obs_popup", "obs_coffee"],
    introTemplates: [
      "월요일이 추격을 시작했다",
      "결재 라인이 다가온다",
      "{input}... 빤쓰가 달린다",
      "부장님 카톡 '1'이 안 사라진다",
      "퇴근까지 8시간, 갓생은 내일부터",
      "야근의 그림자가 길어진다",
      "회의 소집 알림이 울렸다",
      "월급날은 멀고 텅장은 가깝다",
    ],
    resultTemplates: [
      "출근 압박에서 {time}초 버텼다",
      "결재 지옥을 {distance}m 회피했다",
      "야근 {coins}개를 피해 달아났다",
      "부장님 호출을 {near}번 손절했다",
      "{distance}m 도망쳤지만 내일 또 출근… 현타 온다",
      "정시 퇴근의 꿈, {time}초 만에 증발",
      "업무 카톡 {coins}개 읽씹하고 튀었다",
      "{score}점어치 월급루팡 성공",
      "월요병 {distance}m 따돌렸다, 럭키비키🍀",
    ],
    emotionFallback: "Tired",
  },
  School: {
    id: "School",
    label: "학교",
    keywords: [
      "학교", "시험", "중간고사", "기말고사", "발표", "숙제", "과제",
      "수업", "선생님", "공부", "조별", "학점", "교수", "레포트",
    ],
    characterStyleTags: ["student", "uniform"],
    backgroundIds: ["bg_school_hall", "bg_classroom"],
    obstacleIds: ["obs_textbook", "obs_teacher", "obs_homework", "obs_quiz"],
    introTemplates: [
      "시험이 추격을 시작했다",
      "조별 과제가 다가온다",
      "{input}... 교실을 탈출하자",
      "출석 부르는 소리가 들린다",
      "수행평가 마감이 코앞이다",
      "공부는 내일부터, 오늘은 도망부터",
      "조장의 카톡이 울린다",
    ],
    resultTemplates: [
      "발표 공포에서 {time}초 버텼다",
      "숙제 지옥을 {distance}m 도망쳤다",
      "{coins}개의 과제를 외면했다",
      "조장 카톡을 {near}번 읽씹하며 질주",
      "시험 범위는 몰라도 {distance}m는 안다",
      "출석체크 직전 {time}초간 잠적",
      "{score}점 받았는데 시험 점수면 좋겠다",
      "공부 감 다 죽었지만 도망 감은 살아있다",
      "야자 째고 {distance}m 직진, 갓생은 실패",
    ],
    emotionFallback: "Awkward",
  },
  Romance: {
    id: "Romance",
    label: "연애",
    keywords: [
      "소개팅", "썸", "연애", "이별", "헤어져", "헤어진", "고백",
      "차였", "전남친", "전여친", "데이트", "짝사랑", "크러쉬",
    ],
    characterStyleTags: ["heartbreak", "romance"],
    backgroundIds: ["bg_cafe", "bg_park"],
    obstacleIds: ["obs_heart", "obs_ex", "obs_message", "obs_bouquet"],
    introTemplates: [
      "썸의 그림자가 다가온다",
      "헤어진 연인의 추억이 추격한다",
      "{input}... 도망치자, 빤쓰야",
      "전 애인의 결혼 소식이 날아왔다",
      "읽씹당한 카톡이 쫓아온다",
      "삼귀던 그 사람이 잠수탔다",
    ],
    resultTemplates: [
      "이별에서 {time}초 버텼다",
      "연애 후유증 {distance}m 도망 성공",
      "{coins}개의 읽씹 알림을 피했다",
      "전 애인 SNS를 {near}번 참고 안 봤다",
      "미련 {coins}스푼 버리고 {distance}m 질주",
      "새벽 감성 카톡, {time}초 만에 참아냈다",
      "썸은 끝났어도 {distance}m는 영원하다",
      "솔로 탈출은 실패, 도망은 {score}점",
      "전 애인 손절하고 {distance}m 달렸다",
    ],
    emotionFallback: "Awkward",
  },
  Military: {
    id: "Military",
    label: "군대",
    keywords: [
      "군대", "훈련", "훈련소", "상병", "병장", "행군", "점호",
      "내무반", "간부", "유격", "PX", "포상",
    ],
    characterStyleTags: ["soldier"],
    backgroundIds: ["bg_barracks", "bg_field"],
    obstacleIds: ["obs_helmet", "obs_sergeant", "obs_pack", "obs_whistle"],
    introTemplates: [
      "점호 시간이 다가온다",
      "행군이 시작됐다",
      "{input}... 탈영 아님, 그냥 운동",
      "기상나팔이 울렸다",
      "부소대장의 호각이 들린다",
      "남은 군 생활이 추격해온다",
    ],
    resultTemplates: [
      "훈련에서 {time}초 버텼다",
      "행군 {distance}m 완주",
      "PX 간식 {coins}개 확보",
      "점호를 {near}번 아슬하게 피했다",
      "남은 군 생활보다 {time}초가 더 길더라",
      "위병소 앞 {distance}m… 존버의 결실",
      "건빵 {coins}봉지 사수",
      "{score}점이면 포상휴가 주나요",
      "말년 감성으로 {distance}m 버텼다",
    ],
    emotionFallback: "Fear",
  },
  Family: {
    id: "Family",
    label: "가족",
    keywords: [
      "엄마", "아빠", "부모님", "명절", "시댁", "친척", "잔소리",
      "용돈", "결혼", "취업", "언제", "시집", "장가",
    ],
    characterStyleTags: ["home"],
    backgroundIds: ["bg_home", "bg_dining"],
    obstacleIds: ["obs_mom", "obs_relative", "obs_kimchi", "obs_call"],
    introTemplates: [
      "명절이 추격한다",
      "엄마의 잔소리가 시작됐다",
      "{input}... 친척 모임 탈출!",
      "'결혼 언제'가 날아온다",
      "큰집 가는 길이 막혔다",
      "용돈 앞에 잔소리가 따라온다",
    ],
    resultTemplates: [
      "잔소리에서 {time}초 버텼다",
      "친척 질문 {distance}m 회피",
      "{coins}개의 비교 발언을 피했다",
      "'결혼 언제?'를 {near}번 못 들은 척했다",
      "용돈 {coins}만원 받고 {distance}m 줄행랑",
      "사촌과 비교당하기 전 {time}초 만에 탈출",
      "{score}점인데 취업은 아직이라고요",
      "전 부치다 말고 {distance}m 도주, 현타",
      "엄마 잔소리 손절하고 {distance}m 질주",
    ],
    emotionFallback: "Tired",
  },
  Reality: {
    id: "Reality",
    label: "현실",
    keywords: [],
    characterStyleTags: ["casual"],
    backgroundIds: ["bg_street", "bg_city"],
    obstacleIds: ["obs_bill", "obs_rain", "obs_news", "obs_time"],
    introTemplates: [
      "현실이 추격을 시작했다",
      "{input}... 그래, 도망치자",
      "빤쓰는 오늘도 달린다",
      "텅장이 쫓아온다",
      "월요병이 다가온다",
      "현생이 코앞까지 왔다",
    ],
    resultTemplates: [
      "현실에서 {time}초 버텼다",
      "{distance}m 도망 성공",
      "걱정 {coins}개를 뿌리쳤다",
      "스트레스를 {near}번 아슬하게 피했다",
      "{distance}m 도망쳐도 현생은 그대로… 현타",
      "텅장과 함께 {distance}m 질주",
      "{score}점만큼 마음이 가벼워졌다",
      "내일 걱정은 내일의 빤쓰가, 럭키비키🍀",
      "번아웃 {distance}m 따돌렸다",
    ],
    emotionFallback: "Tired",
  },
};

export const CATEGORY_ORDER: Array<Exclude<SituationCategory, "None">> = [
  "Company",
  "School",
  "Romance",
  "Military",
  "Family",
  "Reality",
];
